### ISSUE TITLE
多台服务器用同一个Docker镜像启动只显示一个节点

### ISSUE THREAD

**Issue by tikazyq** [tikazyq/crawlab#99]
Crawlab用MAC做的node的唯一识别号，如果在多个服务器用同一个docker镜像，就会出现MAC地址冲突的情况，导致显示只有一个节点的情况

**Comment by wo10378931** [comment]
个人觉得这个这个问题不需要修改。在两台服务器上，docker默认配置的情况下，运行的容器的IP确实是一样的。建议使用`docker-compose.yml`编排。提供一份示例：
```
version: '3'
services:
  worker:
    image: crawlab:worker
    container_name: crawlab-worker
    volumes:
    - $PWD/conf/config.yml:/opt/crawlab/conf/config.yml
    networks:
      - crawlabnet

networks:
  crawlabnet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
```
